### ISSUE TITLE
Wewnętrzny serwer - czas uśpienia

### ISSUE THREAD

**Issue by motomouse** [piotrekcrash/kodi#5]
Czy wewnętrzny serwer ma jakiś timeout/czas uśpienia ? Po jakimś czasie nie używania TV, streamy ToyaGO przez IPTV Simple są niedostępne. Trzeba wtedy uruchomić wtyczkę ToyaGO i wszystko wraca do normy. Można dodać ustawienie tego czasu we wtyczce ?

**Comment by piotrekcrash** [comment]
Zachowanie nie zamierzone, ale już widzę możliwą przyczynę więc pewnie niedługo pojawi się update.
Generalnie sytuacja nie powinna wystąpić i kanały w PVR powinny działać niezależni od użytkowania wtyczki w menu Dodatków.

**Comment by piotrekcrash** [comment]
Naprawione poprawka w repo - wersja: 2.3.8
Jakby problem nadal występował to daj znać

**Comment by nalewkababuni** [comment]
Potwierdzam. U siebie też to zauważyłem.

**Comment by motomouse** [comment]
Po aktualizacji Kodi do 18.7 sytuacja powtarza się - poradzisz coś ?

**Comment by piotrekcrash** [comment]
@motomouse sprawdzone po aktualizacji do 18.7 i działa poprawnie na Windowsie.
Dodaj swoje logi.

**Comment by motomouse** [comment]
@piotrekcrash 

> 2020-05-27 21:58:58.258 T:18691  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Wszystkie/pvr.iptvsimple_884685947.pvr
2020-05-27 21:58:58.261 T:8149  NOTICE: Creating InputStream
2020-05-27 21:59:02.853 T:18744   ERROR: ToyaGO - 'NoneType' object has no attribute 'get'
2020-05-27 21:59:02.854 T:8149   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2020-05-27 21:59:02.854 T:8149   ERROR: CCurlFile::Open failed with code 0 for http://localhost:8899/channel?id=hbo-hd:
2020-05-27 21:59:07.769 T:18744   ERROR: ToyaGO - 'NoneType' object has no attribute 'get'
2020-05-27 21:59:07.769 T:8149   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2020-05-27 21:59:07.770 T:8149   ERROR: CCurlFile::Open failed with code 0 for http://localhost:8899/channel?id=hbo-hd:
2020-05-27 21:59:07.770 T:8149   ERROR: Open - failed to open source <http://localhost:8899/channel?id=hbo-hd>
2020-05-27 21:59:07.770 T:8149   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Wszystkie/pvr.iptvsimple_884685947.pvr]
2020-05-27 21:59:07.770 T:8149  NOTICE: CVideoPlayer::OnExit()
2020-05-27 21:59:07.820 T:18691  NOTICE: CVideoPlayer::CloseFile()
2020-05-27 21:59:07.822 T:18691  NOTICE: VideoPlayer: waiting for threads to exit
2020-05-27 21:59:07.823 T:18691  NOTICE: VideoPlayer: finished waiting

Takie wystarczą czy chcesz pełne ?

**Comment by piotrekcrash** [comment]
@motomouse problem jest taki sam jak poprzednio, czyli po jakimś czasie przestaje działać Telewizja, ale włączenie programu w dodatku ToyaGO naprawia problem na kolejny okres czasu?
Ile czasu mniej więcej potrzeba, żeby osiągnąć takie efekt?

**Comment by motomouse** [comment]
@piotrekcrash nie do końca. Jesli ogladam programy z listy Toya, to dziala to caly czas. Jak przełączę na program z listy np. WP pilot, to po dluzszym czasie ogladania ( ok. 1 h ) programy Toya nie działają. Trzeba wtedy wejść w dodatek, w podmenu Telewizja - trzeba poczekać na załadowanie się listy. Tak samo dzieje sie jak np. włączę jakiś plik video. Restart Kodi tez zalatwia sprawę.

**Comment by piotrekcrash** [comment]
@motomouse zrobiłem pewne poprawki ale nie puszczam ich do Repo. Tutaj masz testową wersję:
[plugin.video.toyago-2.3.9.zip](https://github.com/piotrekcrash/kodi/files/4693995/plugin.video.toyago-2.3.9.zip)

**Comment by motomouse** [comment]
> 2020-05-28 18:49:46.536 T:20492   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 543-544: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/main.py", line 441, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/main.py", line 409, in router
                                                channelsTv()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/main.py", line 165, in channelsTv
                                                addChannelsTv(listing)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/main.py", line 179, in addChannelsTv
                                                channels = BROWS_API.getTvChannels(cids)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/tv.py", line 30, in getTvChannels
                                                soap = client.authRequest(API_CAT, True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/client.py", line 30, in authRequest
                                                soap = get(session, url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/client.py", line 61, in get
                                                control.logInfo('GET_RESPONSE: ' + r.text)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.toyago/control.py", line 116, in logInfo
                                                xbmc.log(msg=addonname + ' - ' + info, level=xbmc.LOGNOTICE)
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 543-544: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-05-28 18:49:46.654 T:20491   ERROR: GetDirectory - Error getting plugin://plugin.video.toyago/?action=channelsTv
2020-05-28 18:49:46.666 T:20411   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.toyago/?action=channelsTv) failed

**Comment by piotrekcrash** [comment]
@motomouse zostawiłem loggery, żeby w razie czego mieć więcej logów ale jest problem z encodingiem wiec wyrzuciłem i zostawiłem samą poprawkę:
[plugin.video.toyago-2.3.9.zip](https://github.com/piotrekcrash/kodi/files/4697170/plugin.video.toyago-2.3.9.zip)

**Comment by motomouse** [comment]
OK, na nowej wersji da się odpalić TV - potestuję i dam znać.

**Comment by piotrekcrash** [comment]
@motomouse brak odzewu rozumiem jako brak problemów. Zamykam
